name: poiBuild

on: 
 push: 
  #  paths:
  #   - 'apis/poi/**'
   branches:
    - master
 pull_request:
    branches:
      - master
    paths:
      - 'apis/poi/**'
 
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.1

    - name: Install dependencies
      working-directory: ./apis/poi
      run: dotnet restore

    - name: Build
      working-directory: ./apis/poi
      run: dotnet build --configuration Release --no-restore

    - name: Test
      working-directory: ./apis/poi/tests/UnitTests
      run: dotnet test

    - name: Azure Login
      run: echo $GITHUB_RUN_NUMBER
        
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    


    - name: Azure CLI script
      workingDirectory: ./apis/poi/tests/UnitTests    
      uses: azure/CLI@v1
      with:
        azcliversion: 2.0.72
        inlineScript: |
          az account show
          az storage -h
          az acr build --image "openhacks3u8wqs3acr.azurecr.io/api-poi" --registry openhacks3u8wqs3acr --file Dockerfile .

    # - name: Build container
    #     uses: azure/CLI@v1
    #     with:
    #       azcliversion: 2.0.72
    #       inlineScript: |
    #         az acr build --image "openhacks3u8wqs3acr.azurecr.io/api-poi:{{$GITHUB_RUN_NUMBER}}" --registry openhacks3u8wqs3acr --file Dockerfile .

          



          



     
    - uses: actions/github-script@0.9.0
      if: failure()
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          let body = "${{ env.build_name }} Worflow Failure \n Build Number: ${{ github.run_number }} \n Build Log: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }} \n SHA: [${{ github.sha }}](https://github.com/${{ github.repository }}/commit/${{ github.sha }}) \n";
          github.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: "${{ env.build_name }} Workflow ${{ github.run_number }} Failed! ",
            body: body
          });
      

